# MoveIt Servo Configuration
use_gazebo: false
status_topic: servo_node/status
command_out_topic: /joint_trajectory_controller/joint_trajectory
command_out_type: trajectory_msgs/JointTrajectory

move_group_name: left_arm 
planning_frame: world

is_primary_joint_variable: false
check_collisions: true
collision_check_rate: 10.0

smoothing_filter_coeff: 0.1 
